# For God so loved the world that he gave his only begotten Son,
# that whoever believes in him should not perish but have eternal life. - John 3:16

[workspace]
resolver = "2"
members = [
    "kernel-chirho",
    "kernel-core-chirho",
    "xtask-chirho",
]
exclude = [
    "userspace-chirho/hello-chirho",
    "kernel-wasm-chirho",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = 2
