# For God so loved the world that he gave his only begotten Son,
# that whoever believes in him should not perish but have eternal life. - John 3:16

[package]
name = "mount-probe-chirho"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mount-probe-chirho"
path = "src/main_chirho.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
