# For God so loved the world that he gave his only begotten Son,
# that whoever believes in him should not perish but have eternal life. - John 3:16

[package]
name = "kernel-chirho"
version = "0.1.0"
edition = "2021"
authors = ["Lineluya Project"]
description = "Lineluya - A Linux kernel rewrite in Rust"

[[bin]]
name = "kernel-chirho"
path = "src/main_chirho.rs"

[dependencies]
bootloader_api = "0.11"
x86_64 = { version = "0.15", features = ["instructions"] }
spin = "0.9"

pc-keyboard = "0.8"
buddy-alloc = "0.6"
log = "0.4"
